### PR TITLE
DM-11050: Remove all refs to LDM-472.

### PR DESCRIPTION
**Pull request by jdswinbank**

### CODE REVIEW

**Review by womullan — APPROVED** [review]

**Comment by womullan** [comment]
so should we baseline this as well now ..   and wht is the process to make LDM-472 obsoloete

**Comment by timj** [comment]
LPM-51 has a mechanism for obsoleting documents in DocuShare. Re baselining DMTN-020 I thought we had explicitly separated LDM-472 and DMTN-020 such that we wouldn't be worrying about change control for the 020 content.

**Comment by womullan** [comment]
sorry two questions. we have updated DMTN-020 on my branch - I think it could be merged to master.

**Comment by jdswinbank** [comment]
> LPM-51 has a mechanism for obsoleting documents in DocuShare

Specifically: "the title of the previous document shall be edited to indicate its obsolescence and an “Obsolete Document Referral Page” (Document-12321) shall be uploaded as the preferred version of the obsolete handle".

> Re baselining DMTN-020 I thought we had explicitly separated LDM-472 and DMTN-020 such that we wouldn't be worrying about change control for the 020 content.

I agree with this.

**Comment by jdswinbank** [comment]
Yes, let's merge DMTN-020 to master.

**Pull request merged**
